In [16]:
# Tensorflow and Keras are two packages for creating neural network models.
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split

# import NN layers and other componenets.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense, BatchNormalization, Dropout
from tensorflow.keras import optimizers
import matplotlib.pyplot as plt # for plotting data and creating different charts.
import numpy as np # for math and arrays
import pandas as pd # data from for the data.
import seaborn as sns # for plotting.

In [11]:
df=pd.read_csv("pima-indians.csv", header=None)
df.head(10)

0    1   2   3    4     5      6   7         8         9   ...  21  22  23  \
0   6  148  72  35    0  33.6  0.627  58  0.582016  0.351544  ...  50  51  35   
1   1   85  66  29    0  26.6  0.351  97  0.832630  0.110514  ...  31  32  29   
2   8  183  64   0    0  23.3  0.672  51  0.305414  0.335498  ...  32  33   0   
3   1   89  66  23   94  28.1  0.167  16  0.175202  0.431177  ...  21  22  23   
4   0  137  40  35  168  43.1  2.288   9  0.041532  0.254211  ...  33  34  35   
5   5  116  74   0    0  25.6  0.201   6  0.796317  0.620558  ...  30  31   0   
6   3   78  50  32   88  31.0  0.248  42  0.649129  0.033726  ...  26  27  32   
7  10  115   0   0    0  35.3  0.134  28  0.423688  0.518020  ...  29  30   0   
8   2  197  70  45  543  30.5  0.158  74  0.461396  0.408169  ...  53  54  45   
9   8  125  96   0    0   0.0  0.232   2  0.288525  0.359993  ...  54  55   0   

    24    25     26  27        28  29  30  
0    0  33.6  0.627  66  0.073498   1   1  
1    0  26.6  0.351  67  0.296772   1   2  
2    0  23.3  0.672  83  0.092107   6   3  
3   94  28.1  0.167  31  0.246629   8   4  
4  168  43.1  2.288  62  0.301854   3   5  
5    0  25.6  0.201  32  0.503962   9   1  
6   88  31.0  0.248  81  0.575259   4   2  
7    0  35.3  0.134  55  0.473132   7   3  
8  543  30.5  0.158  50  0.868384   6   4  
9    0   0.0  0.232  68  0.788383   6   5  

[10 rows x 31 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       768 non-null    int64  
 1   1       768 non-null    int64  
 2   2       768 non-null    int64  
 3   3       768 non-null    int64  
 4   4       768 non-null    int64  
 5   5       768 non-null    float64
 6   6       768 non-null    float64
 7   7       768 non-null    int64  
 8   8       768 non-null    float64
 9   9       768 non-null    float64
 10  10      768 non-null    float64
 11  11      768 non-null    float64
 12  12      768 non-null    float64
 13  13      768 non-null    float64
 14  14      768 non-null    float64
 15  15      768 non-null    float64
 16  16      768 non-null    int64  
 17  17      768 non-null    float64
 18  18      768 non-null    int64  
 19  19      768 non-null    int64  
 20  20      768 non-null    int64  
 21  21      768 non-null    int64  
 22  22

In [13]:
df.describe()

0           1           2           3           4           5   \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

               6           7           8           9   ...          21  \
count  768.000000  768.000000  768.000000  768.000000  ...  768.000000   
mean     0.471876   48.911458    0.502363    0.509221  ...   33.240885   
std      0.331329   29.356772    0.284582    0.285739  ...   11.760232   
min      0.078000    1.000000    0.001607    0.002182  ...   21.000000   
25%      0.243750   23.000000    0.255150    0.265821  ...   24.000000   
50%      0.372500   47.000000    0.506342    0.495043  ...   29.000000   
75%      0.626250   75.000000    0.744777    0.745594  ...   41.000000   
max      2.420000  100.000000    0.999659    0.999098  ...   81.000000   

               22          23          24          25          26          27  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean    34.240885   20.536458   79.799479   31.992578    0.471876   49.942708   
std     11.760232   15.952218  115.244002    7.884160    0.331329   28.204863   
min     22.000000    0.000000    0.000000    0.000000    0.078000    1.000000   
25%     25.000000    0.000000    0.000000   27.300000    0.243750   26.750000   
50%     30.000000   23.000000   30.500000   32.000000    0.372500   51.000000   
75%     42.000000   32.000000  127.250000   36.600000    0.626250   73.000000   
max     82.000000   99.000000  846.000000   67.100000    2.420000  100.000000   

               28          29          30  
count  768.000000  768.000000  768.000000  
mean     0.499174    5.691406    2.555990  
std      0.297853    2.869128    1.385148  
min      0.003838    1.000000    0.000000  
25%      0.239481    3.000000    2.000000  
50%      0.500552    6.000000    2.000000  
75%      0.753453    8.000000    4.000000  
max      0.999775   10.000000    5.000000  

[8 rows x 31 columns]

In [14]:
X_data = df.iloc[:, 0:29]
Y_data = df.iloc[:, 30]

In [19]:
from sklearn.model_selection import train_test_split
train_X,test_X,train_Y,test_Y = train_test_split(X_data, Y_data, test_size=0.2, random_state=13)

train_X.shape,valid_X.shape

((614, 29), (154, 29))

In [21]:
# Split the test_dataset dataframe to 50% test and 50% validation. [this will divide the dataset into 60% train, 20% validate, and 20% test]
test_X,valid_X,test_Y,valid_Y =  train_test_split(test_X,test_Y, test_size=0.5)
test_X.shape,valid_X.shape

((38, 29), (39, 29))

In [38]:
from tensorflow.keras.utils import to_categorical

# Change the labels from categorical to one-hot encoding
train_Y_one_hot = to_categorical(train_Y, num_classes = 6)
test_Y_one_hot = to_categorical(test_Y, num_classes = 6)
valid_Y_one_hot = to_categorical(valid_Y, num_classes = 6)

# Display the change for category label using one-hot encoding
print('Original label:', np.unique(train_Y))
print('After conversion to one-hot:', train_Y_one_hot)

Original label: [0 1 2 3 4 5]
After conversion to one-hot: [[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]


In [26]:
train_stats = train_X.describe()
train_stats = train_stats.transpose()
train_stats['mean']

0       3.845277
1     120.325733
2      69.605863
3      20.767101
4      77.408795
5      31.964984
6       0.464200
7      50.066775
8       0.516622
9       0.510510
10     34.184183
11     13.585230
12     20.498976
13     79.464027
14     31.893646
15      0.462671
16     49.495114
17      0.495525
18      5.703583
19     33.143322
20      5.503257
21     33.143322
22     34.143322
23     20.767101
24     77.408795
25     31.964984
26      0.464200
27     49.495114
28      0.495525
Name: mean, dtype: float64

In [28]:
# define a function to normalize the data set.
def norm(x):
    return (x - train_stats['mean']) / train_stats['std']

normed_train_data = norm(train_X)
normed_test_data = norm(test_X)
normed_valid_dataset = norm(valid_X)

In [23]:
# Find the unique numbers from the train labels
classes = np.unique(train_Y)
nClasses = len(classes)
print('Total number of outputs : ', nClasses)
print('Output classes : ', classes)

Total number of outputs :  6
Output classes :  [0 1 2 3 4 5]


In [32]:
# We decalred a function for creating a model.
def build_model1_four_hidden_layers():
    model = Sequential()
    model.add(Dense(30, input_shape = (normed_train_data.shape[1],)))    # Input layer    
    model.add(Dense(18, activation='softmax'))  
    model.add(Dense(9, activation='softmax'))   
    model.add(Dense(nClasses, activation='softmax'))
    

    learning_rate = 0.0001
    optimizer = optimizers.Adam(learning_rate)
    model.compile(loss='categorical_crossentropy',
                optimizer=optimizer,
                metrics=['accuracy'])
    return model


EPOCHS = 100
batch_size = 16 # 6 iteration

model = build_model1_four_hidden_layers()
print('Here is a summary of this model: ')
model.summary()

Here is a summary of this model: 
Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 30)                900       
_________________________________________________________________
dense_11 (Dense)             (None, 18)                558       
_________________________________________________________________
dense_12 (Dense)             (None, 9)                 171       
_________________________________________________________________
dense_13 (Dense)             (None, 6)                 60        
Total params: 1,689
Trainable params: 1,689
Non-trainable params: 0
_________________________________________________________________


In [33]:
batch_size = 64
epochs = 50
num_classes = 2

In [35]:
model_train = model.fit(normed_train_data, train_Y_one_hot, batch_size=batch_size, epochs=epochs, verbose=1, validation_data=(normed_test_data, valid_Y))

ValueError: You are passing a target array of shape (614, 1) while using as loss `categorical_crossentropy`. `categorical_crossentropy` expects targets to be binary matrices (1s and 0s) of shape (samples, classes). If your targets are integer classes, you can convert them to the expected format via:
```
from keras.utils import to_categorical
y_binary = to_categorical(y_int)
```

Alternatively, you can use the loss function `sparse_categorical_crossentropy` instead, which does expect integer targets.